/** Approved CSS color-token names shared by Storefront and Admin. */
export const colorTokenNames = [
  'base-white',
  'base-black',
  'primary-50',
  'primary-100',
  'primary-200',
  'primary-300',
  'primary-400',
  'primary-500',
  'primary-600',
  'primary-700',
  'primary-800',
  'primary-900',
  'primary-950',
  'secondary-50',
  'secondary-100',
  'secondary-200',
  'secondary-300',
  'secondary-400',
  'secondary-500',
  'secondary-600',
  'secondary-700',
  'secondary-800',
  'secondary-900',
  'secondary-950',
  'gray-25',
  'gray-50',
  'gray-100',
  'gray-200',
  'gray-300',
  'gray-400',
  'gray-500',
  'gray-600',
  'gray-700',
  'gray-800',
  'gray-900',
  'gray-950',
  'violet-500',
  'amber-500',
  'fuchsia-500',
  'background',
  'foreground',
  'surface',
  'surface-muted',
  'surface-elevated',
  'text-secondary',
  'border',
  'input',
  'ring',
  'primary',
  'primary-hover',
  'primary-subtle',
  'primary-foreground',
  'accent',
  'accent-foreground',
  'success',
  'success-foreground',
  'warning',
  'warning-foreground',
  'destructive',
  'destructive-foreground',
  'info',
  'info-foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'muted',
  'muted-foreground',
  'sidebar',
  'sidebar-foreground',
] as const

export type ColorTokenName = (typeof colorTokenNames)[number]

export const colorThemeClassNames = {
  light: 'light',
  dark: 'dark',
} as const
